name: Update Yandex Tracker

on:
  pull_request:
    types: [opened, closed]

jobs:
  update_tracker_on_pr_open:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Set task status to "Review"
        run: |
          TASK_ID=$(echo FR-5 варс в ридми, а не сикретс | grep -o '[A-Z]*-[0-9]*')
          if [ -z "$TASK_ID" ]; then
            echo "No task ID found in the pull request title."
            exit 1
          fi

          # Debugging output
          echo "Task ID: $TASK_ID"

          curl -X POST \
            https://api.tracker.yandex.net/v2/issues/$TASK_ID/transitions \
            -H "Authorization: OAuth ${{ vars.YANDEX_OAUTH_TOKEN }}" \
            -H "X-Org-ID: ${{ vars.YANDEX_ORG_ID }}" \
            -H "Content-Type: application/json" \
            -d '{"transition":{"id":"inReview"}}'

  update_tracker_on_pr_merge:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Set task status to "Testing"
        run: |
          TASK_ID=$(echo ${{ github.event.pull_request.title }} | grep -o '[A-Z]*-[0-9]*')
          if [ -z "$TASK_ID" ]; then
            echo "No task ID found in the pull request title."
            exit 1
          fi
          curl -X POST \
            https://api.tracker.yandex.net/v2/issues/$TASK_ID/transitions \
            -H "Authorization: OAuth ${{ secrets.YANDEX_OAUTH_TOKEN }}" \
            -H "X-Org-ID: ${{ secrets.YANDEX_ORG_ID }}" \
            -H "Content-Type: application/json" \
            -d '{"transition":{"id":"testing"}}'
