name: Yandex Tracker Workflow

on:
  push:
    branches:
      - 'FR-*'
  pull_request:
    types:
      - closed

jobs:
  update_tracker:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Check if commit contains task code
      if: github.event_name == 'push'
      run: |
        TASK_CODE=$(echo ${{ github.ref }} | grep -oP '(?<=FR-)\d+')
        COMMIT_MSG=$(git log -1 --pretty=%B)
        if echo "$COMMIT_MSG" | grep -q "FR-$TASK_CODE"; then
          echo "Task code found in commit message"
          echo "TASK_CODE=$TASK_CODE" >> $GITHUB_ENV
        else
          echo "Task code not found in commit message"
          exit 1
        fi

    - name: Update Yandex Tracker to 'Review'
      if: github.event_name == 'push' && env.TASK_CODE
      run: |
        curl -X POST "https://tracker.yandex.ru/api/v2/issues/FR-${{ env.TASK_CODE }}/transitions" \
          -H "Authorization: Bearer ${{ secrets.YANDEX_OAUTH_TOKEN }}" \
          -H "X-Org-ID: ${{ secrets.YANDEX_ORG_ID }}" \
          -H "Content-Type: application/json" \
          -d '{"transition": {"id": "inReview"}}'

    - name: Check if pull request is merged
      if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
      run: |
        TASK_CODE=$(echo ${{ github.head_ref }} | grep -oP '(?<=FR-)\d+')
        echo "TASK_CODE=$TASK_CODE" >> $GITHUB_ENV

    - name: Update Yandex Tracker to 'Testing'
      if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && env.TASK_CODE
      run: |
        curl -X POST "https://tracker.yandex.ru/api/v2/issues/FR-${{ env.TASK_CODE }}/transitions" \
          -H "Authorization: Bearer ${{ secrets.YANDEX_OAUTH_TOKEN }}" \
          -H "X-Org-ID: ${{ secrets.YANDEX_ORG_ID }}" \
          -H "Content-Type: application/json" \
          -d '{"transition": {"id": "testing"}}'
